### ISSUE TITLE
SMTIO crashes with IndexError: string index out of range

### ISSUE THREAD

**Issue by ZipCPU** [cliffordwolf/yosys#436]
When running

yosys-smtbmc --presat -s yices -t 24 --dump-smt2 wbm2axisp_bmc.smt2 --dump-vcd wbm2axisp_bmc.vcd wbm2axisp.smt2

I'm getting the following error,

```
...
##      0   0:00:00  BMC failed!
Traceback (most recent call last):
  File "/usr/local/bin/yosys-smtbmc", line 1227, in <module>
    print_failed_asserts(i)
  File "/usr/local/bin/yosys-smtbmc", line 961, in print_failed_asserts
    if print_failed_asserts_worker(topmod, "s%d" % state, topmod, extrainfo):
  File "/usr/local/bin/yosys-smtbmc", line 935, in print_failed_asserts_worker
    if smt.get("(|%s_a| %s)" % (mod, state)) in ["true", "#b1"]:
  File "/usr/local/bin/../share/yosys/python3/smtio.py", line 562, in get
    return self.parse(self.read())[0][1]
  File "/usr/local/bin/../share/yosys/python3/smtio.py", line 527, in parse
    return worker(stmt)[0]
  File "/usr/local/bin/../share/yosys/python3/smtio.py", line 498, in worker
    if stmt[0] == '(':
IndexError: string index out of range
```

If you look into smtio.py, near line 498, there's no bounds checking in the parse(self, stmt): worker(stmt) function.  I think this is what's going on.

Dan

**Comment by cliffordwolf** [comment]
Received MVCE via DM. Looking into it now..

**Comment by cliffordwolf** [comment]
This is a bug in Yices2: https://github.com/SRI-CSL/yices2/issues/81

Workaround for now: Use `boolector` or `z3` for this project.

**Comment by cliffordwolf** [comment]
Fixed in Yices. Update to latest git HEAD of Yices to resolve this issue.
